let logo = document.querySelector(".logo");
let header = document.getElementById("header");
let nav_bar=document.querySelector(".nav-bar");
let man=document.getElementById("photoman")
document.body.onscroll=()=>{
    if(document.documentElement.scrollTop>0)
    {
        logo.style.width="154px"
        logo.style.height="51px"
        logo.style.marginBottom="15px"
        header.style.backgroundColor="black"
        // nav_bar.style.marginTop="-35px"
        console.log(document.documentElement.scrollTop)
        if(document.documentElement.scrollTop>=200)
        {
         man.style.top="150px"
        }
    }
    else{
        man.style.top="120px"
        logo.style.width="220px"
        logo.style.height="75px"
        nav_bar.style.marginTop="-50px"
        header.style.backgroundColor="transparent"
    }
}

itemsjs=[{
    id:"dollar",
    text:"The SSB Token will generate large amounts of buying pressure and accelerated hyper deflationary burns with our unique tokenomics and multiple use cases."
},
{
    id:"bar",
    text:"The Leviathan buyback combined with our innovative lottery buyback will ensure a constant accelerated hyper-deflationary burn."
},
{
    id:"sale",
    text:"and burns are generated by requiring SSB clients to BUY and BURN a set amount of SSB Tokens before paying the remaining balance."
}
,{
    id:"gift-card",
    text:"kExclusive access to “The Streets” NFT Marketplace and SSB Radio contests/giveaways"
},
{id:"stack",
text:"Stake SSB to earn WSB and a wide variety of other tokens listed on the staking platform."
}
]

let items= document.querySelectorAll(".item");
items.forEach(item => {
    item.onpointerenter=()=>{
          
        for (let i = 0; i < itemsjs.length; i++) {
               
            if(item.id===itemsjs[i].id)
            {
                item.children[2].children[0].innerHTML=itemsjs[i].text ;     
                item.children[2].children[0].classList.add("divghost");
            }   

        }

    }
});
items.forEach(item => {
    item.onpointerleave=()=>{
          
        for (let i = 0; i < itemsjs.length; i++) {
               
            if(item.id===itemsjs[i].id)
            {
                item.children[2].children[0].innerHTML=""
                item.children[2].children[0].classList.remove("divghost");
        
            }   

        }

    }
});

//nav-bar qery @media  (max-width: 768px)
let burger=document.querySelector(".burger")
    ,nav_lis=document.querySelector(".nav-bar");
    burger.addEventListener("click",function(){
    let row1=document.getElementById("row1")
    let row2=document.getElementById("row2")
    let row3=document.getElementById("row3")
        nav_lis.classList.toggle('trans');
        row1.classList.toggle('rows1')
        row2.classList.toggle('rows2')
        row3.classList.toggle('rows3')
    })








